
package Views;

import Controllers.ConfigControllers;
import Controllers.UsuariosControllers;
import Models.Usuarios;
import Models.UsuariosDao;

/**
 *
 * @author Usuario
 */
public class PanelAdmin extends javax.swing.JFrame {
    Usuarios us=new Usuarios();
    UsuariosDao usDao=new UsuariosDao();

    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin() {
       
        
        
    }

    public PanelAdmin(int id, String nombre) {
         initComponents();
        ConfigControllers config=new ConfigControllers(this);
        UsuariosControllers users=new UsuariosControllers(us,usDao,this);
        
        
            
      
TxtIdUsuario.setText(""+id);
BtnUsuario.setText(nombre);
jTabbedPane1.setSelectedIndex(0);
//jTabbedPane1.setEnabled(false);//para desactivar indixe depanel


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPopupUsuarios = new javax.swing.JPopupMenu();
        JMenuEliminarUsers = new javax.swing.JMenuItem();
        JMenuReingresarUsers = new javax.swing.JMenuItem();
        JPanelAdmin = new javax.swing.JPanel();
        JPanelHome = new javax.swing.JPanel();
        JLebelParticipante = new javax.swing.JLabel();
        JPanelParticipante = new javax.swing.JPanel();
        JLebelParticipante1 = new javax.swing.JLabel();
        JPanelUsuarios = new javax.swing.JPanel();
        JLebelUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        TxtIdUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BtnUsuario = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHome = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelUsuarios = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtNombreUser = new javax.swing.JTextField();
        TxtIdUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtUsuarioUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnModificarUser = new javax.swing.JButton();
        BtnNuevoUser = new javax.swing.JButton();
        BtnRegistarUser = new javax.swing.JButton();
        TxtPasswordUser = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        CbxRolUser = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        TxtBuscarUser = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableUsuario = new javax.swing.JTable();
        jPanelParticipante = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TxtBuscarPart = new javax.swing.JTextField();
        TxtNombrePart = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelCursos = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        TxtBuscarCur = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TxtNombreCur = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TxtCodigoCur = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TxtMonbreCur = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        TxtFechaCur = new javax.swing.JTextField();
        BtnNuevoCur = new javax.swing.JButton();
        BtnRegistarCur = new javax.swing.JButton();
        BtnModificarCur = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCursos = new javax.swing.JTable();
        jPanelReportes = new javax.swing.JPanel();

        JMenuEliminarUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-eliminar-30.png"))); // NOI18N
        JMenuEliminarUsers.setText("Eliminar");
        JPopupUsuarios.add(JMenuEliminarUsers);

        JMenuReingresarUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-sincronización-de-conexión-30.png"))); // NOI18N
        JMenuReingresarUsers.setText("Reingresar");
        JPopupUsuarios.add(JMenuReingresarUsers);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelAdmin.setBackground(new java.awt.Color(0, 102, 102));
        JPanelAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelHome.setBackground(new java.awt.Color(255, 255, 255));

        JLebelParticipante.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLebelParticipante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLebelParticipante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-estudiante-40.png"))); // NOI18N
        JLebelParticipante.setText("Home");
        JLebelParticipante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelHomeLayout = new javax.swing.GroupLayout(JPanelHome);
        JPanelHome.setLayout(JPanelHomeLayout);
        JPanelHomeLayout.setHorizontalGroup(
            JPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLebelParticipante, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        JPanelHomeLayout.setVerticalGroup(
            JPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLebelParticipante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JPanelAdmin.add(JPanelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 40));

        JPanelParticipante.setBackground(new java.awt.Color(255, 255, 255));

        JLebelParticipante1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLebelParticipante1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLebelParticipante1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-estudiante-40.png"))); // NOI18N
        JLebelParticipante1.setText("Participante");
        JLebelParticipante1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelParticipanteLayout = new javax.swing.GroupLayout(JPanelParticipante);
        JPanelParticipante.setLayout(JPanelParticipanteLayout);
        JPanelParticipanteLayout.setHorizontalGroup(
            JPanelParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLebelParticipante1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        JPanelParticipanteLayout.setVerticalGroup(
            JPanelParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLebelParticipante1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JPanelAdmin.add(JPanelParticipante, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, 40));

        JPanelUsuarios.setBackground(new java.awt.Color(255, 255, 255));

        JLebelUsuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLebelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLebelUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-usuario-masculino-40.png"))); // NOI18N
        JLebelUsuario.setText("Usuario");
        JLebelUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelUsuariosLayout = new javax.swing.GroupLayout(JPanelUsuarios);
        JPanelUsuarios.setLayout(JPanelUsuariosLayout);
        JPanelUsuariosLayout.setHorizontalGroup(
            JPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLebelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        JPanelUsuariosLayout.setVerticalGroup(
            JPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelUsuariosLayout.createSequentialGroup()
                .addComponent(JLebelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPanelAdmin.add(JPanelUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 40));

        getContentPane().add(JPanelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 480));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRO DE CURSOS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 32));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 90));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(TxtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 30, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("Informática & Programacion");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 490, -1));

        BtnUsuario.setText("User");
        jPanel3.add(BtnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 110, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 780, 90));

        jPanelHome.setBackground(new java.awt.Color(153, 153, 153));
        jPanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setText("Panel de Admin");
        jPanelHome.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 160, 255, 118));

        jTabbedPane1.addTab("Home", jPanelHome);

        jPanelUsuarios.setBackground(new java.awt.Color(0, 153, 0));
        jPanelUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 30));

        TxtNombreUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreUserActionPerformed(evt);
            }
        });
        jPanel8.add(TxtNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 140, 30));

        TxtIdUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdUserActionPerformed(evt);
            }
        });
        jPanel8.add(TxtIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 30, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Id");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 30));

        TxtUsuarioUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioUserActionPerformed(evt);
            }
        });
        jPanel8.add(TxtUsuarioUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 140, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Usuario");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 50, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Rol");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 50, 30));

        BtnModificarUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnModificarUser.setText("Modificar");
        BtnModificarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarUserActionPerformed(evt);
            }
        });
        jPanel8.add(BtnModificarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        BtnNuevoUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnNuevoUser.setText("Nuevo");
        BtnNuevoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoUserActionPerformed(evt);
            }
        });
        jPanel8.add(BtnNuevoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        BtnRegistarUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnRegistarUser.setText("Registar");
        BtnRegistarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistarUserActionPerformed(evt);
            }
        });
        jPanel8.add(BtnRegistarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));
        jPanel8.add(TxtPasswordUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 140, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Clave");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 50, 30));

        CbxRolUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario" }));
        jPanel8.add(CbxRolUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 140, 30));

        jLabel10.setText("Buscar");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));
        jPanel8.add(TxtBuscarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 120, 30));

        jPanelUsuarios.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 450));

        TableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "USUARIO", "ROL", "ESTADO"
            }
        ));
        TableUsuario.setComponentPopupMenu(JPopupUsuarios);
        TableUsuario.setRowHeight(20);
        jScrollPane1.setViewportView(TableUsuario);

        jPanelUsuarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 0, 530, 450));

        jTabbedPane1.addTab("Usuario", jPanelUsuarios);

        jPanelParticipante.setBackground(new java.awt.Color(0, 204, 204));
        jPanelParticipante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Participante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Buscar");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 50, 20));
        jPanel1.add(TxtBuscarPart, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 120, 30));
        jPanel1.add(TxtNombrePart, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 150, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("ID");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 20, 30));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 150, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Dni");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 40, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Nombre");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, 30));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 150, 30));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 150, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Apellidos");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 60, 30));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 150, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("Telefono");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 60, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("Cursos");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 60, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Modificar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 100, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Nuevo");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 100, 30));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Registrar");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 100, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 150, 30));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel22.setText("Email");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 60, 30));
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 150, 30));

        jPanelParticipante.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 450));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI", "NOMBRE", "APELLIDOS", "TELEFONO", "CURSOS"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanelParticipante.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 0, 530, 450));

        jTabbedPane1.addTab("Participante", jPanelParticipante);

        jPanelCursos.setBackground(new java.awt.Color(0, 153, 0));
        jPanelCursos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cursos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText("Buscar");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText("ID");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText("Codigo");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel20.setText("Nombre");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel21.setText("Fecha");

        BtnNuevoCur.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnNuevoCur.setText("Nuevo");

        BtnRegistarCur.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnRegistarCur.setText("Registrar");

        BtnModificarCur.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnModificarCur.setText("Modificar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(TxtBuscarCur, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(TxtNombreCur, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(TxtCodigoCur, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(TxtMonbreCur, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(TxtFechaCur, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BtnRegistarCur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(BtnModificarCur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(BtnNuevoCur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TxtBuscarCur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombreCur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCodigoCur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtMonbreCur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFechaCur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(BtnNuevoCur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnRegistarCur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnModificarCur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 94, Short.MAX_VALUE))
        );

        jPanelCursos.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 450));

        jTableCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo", "Nombre del Curso", "Fecha del Curso", "Estado"
            }
        ));
        jScrollPane3.setViewportView(jTableCursos);

        jPanelCursos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 530, 450));

        jTabbedPane1.addTab("Curso", jPanelCursos);

        javax.swing.GroupLayout jPanelReportesLayout = new javax.swing.GroupLayout(jPanelReportes);
        jPanelReportes.setLayout(jPanelReportesLayout);
        jPanelReportesLayout.setHorizontalGroup(
            jPanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        jPanelReportesLayout.setVerticalGroup(
            jPanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reportes", jPanelReportes);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 780, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreUserActionPerformed

    private void TxtIdUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdUserActionPerformed

    private void TxtUsuarioUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioUserActionPerformed

    private void BtnModificarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModificarUserActionPerformed

    private void BtnNuevoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNuevoUserActionPerformed

    private void BtnRegistarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegistarUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnModificarCur;
    public javax.swing.JButton BtnModificarUser;
    public javax.swing.JButton BtnNuevoCur;
    public javax.swing.JButton BtnNuevoUser;
    public javax.swing.JButton BtnRegistarCur;
    public javax.swing.JButton BtnRegistarUser;
    private javax.swing.JButton BtnUsuario;
    public javax.swing.JComboBox<String> CbxRolUser;
    public javax.swing.JLabel JLebelParticipante;
    public javax.swing.JLabel JLebelParticipante1;
    public javax.swing.JLabel JLebelUsuario;
    public javax.swing.JMenuItem JMenuEliminarUsers;
    public javax.swing.JMenuItem JMenuReingresarUsers;
    private javax.swing.JPanel JPanelAdmin;
    public javax.swing.JPanel JPanelHome;
    public javax.swing.JPanel JPanelParticipante;
    public javax.swing.JPanel JPanelUsuarios;
    private javax.swing.JPopupMenu JPopupUsuarios;
    public javax.swing.JTable TableUsuario;
    public javax.swing.JTextField TxtBuscarCur;
    public javax.swing.JTextField TxtBuscarPart;
    public javax.swing.JTextField TxtBuscarUser;
    public javax.swing.JTextField TxtCodigoCur;
    public javax.swing.JTextField TxtFechaCur;
    public javax.swing.JTextField TxtIdUser;
    private javax.swing.JTextField TxtIdUsuario;
    public javax.swing.JTextField TxtMonbreCur;
    public javax.swing.JTextField TxtNombreCur;
    public javax.swing.JTextField TxtNombrePart;
    public javax.swing.JTextField TxtNombreUser;
    public javax.swing.JPasswordField TxtPasswordUser;
    public javax.swing.JTextField TxtUsuarioUser;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelCursos;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelParticipante;
    private javax.swing.JPanel jPanelReportes;
    private javax.swing.JPanel jPanelUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable jTableCursos;
    public javax.swing.JTextField jTextField10;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
